/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/opd-ai/toxcore/capi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 18 "toxav_c.go"

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

// Forward declarations matching libtoxcore ToxAV API
typedef struct ToxAV ToxAV;
typedef struct Tox Tox;

// Call state enum matching libtoxcore
typedef enum TOX_AV_CALL_STATE {
    TOX_AV_CALL_STATE_NONE = 0,
    TOX_AV_CALL_STATE_ERROR = 1,
    TOX_AV_CALL_STATE_FINISHED = 2,
    TOX_AV_CALL_STATE_SENDING_AUDIO = 4,
    TOX_AV_CALL_STATE_SENDING_VIDEO = 8,
    TOX_AV_CALL_STATE_ACCEPTING_AUDIO = 16,
    TOX_AV_CALL_STATE_ACCEPTING_VIDEO = 32,
} TOX_AV_CALL_STATE;

// Call control enum matching libtoxcore
typedef enum TOX_AV_CALL_CONTROL {
    TOX_AV_CALL_CONTROL_RESUME = 0,
    TOX_AV_CALL_CONTROL_PAUSE = 1,
    TOX_AV_CALL_CONTROL_CANCEL = 2,
    TOX_AV_CALL_CONTROL_MUTE_AUDIO = 3,
    TOX_AV_CALL_CONTROL_UNMUTE_AUDIO = 4,
    TOX_AV_CALL_CONTROL_HIDE_VIDEO = 5,
    TOX_AV_CALL_CONTROL_SHOW_VIDEO = 6,
} TOX_AV_CALL_CONTROL;

// Error enums matching libtoxcore
typedef enum TOX_AV_ERR_NEW {
    TOX_AV_ERR_NEW_OK = 0,
    TOX_AV_ERR_NEW_NULL = 1,
    TOX_AV_ERR_NEW_MALLOC = 2,
    TOX_AV_ERR_NEW_MULTIPLE = 3,
} TOX_AV_ERR_NEW;

typedef enum TOX_AV_ERR_CALL {
    TOX_AV_ERR_CALL_OK = 0,
    TOX_AV_ERR_CALL_MALLOC = 1,
    TOX_AV_ERR_CALL_SYNC = 2,
    TOX_AV_ERR_CALL_FRIEND_NOT_FOUND = 3,
    TOX_AV_ERR_CALL_FRIEND_NOT_CONNECTED = 4,
    TOX_AV_ERR_CALL_FRIEND_ALREADY_IN_CALL = 5,
    TOX_AV_ERR_CALL_INVALID_BIT_RATE = 6,
} TOX_AV_ERR_CALL;

typedef enum TOX_AV_ERR_ANSWER {
    TOX_AV_ERR_ANSWER_OK = 0,
    TOX_AV_ERR_ANSWER_SYNC = 1,
    TOX_AV_ERR_ANSWER_CODEC_INITIALIZATION = 2,
    TOX_AV_ERR_ANSWER_FRIEND_NOT_FOUND = 3,
    TOX_AV_ERR_ANSWER_FRIEND_NOT_CALLING = 4,
    TOX_AV_ERR_ANSWER_INVALID_BIT_RATE = 5,
} TOX_AV_ERR_ANSWER;

typedef enum TOX_AV_ERR_CALL_CONTROL {
    TOX_AV_ERR_CALL_CONTROL_OK = 0,
    TOX_AV_ERR_CALL_CONTROL_SYNC = 1,
    TOX_AV_ERR_CALL_CONTROL_FRIEND_NOT_FOUND = 2,
    TOX_AV_ERR_CALL_CONTROL_FRIEND_NOT_IN_CALL = 3,
    TOX_AV_ERR_CALL_CONTROL_INVALID_TRANSITION = 4,
} TOX_AV_ERR_CALL_CONTROL;

typedef enum TOX_AV_ERR_BIT_RATE_SET {
    TOX_AV_ERR_BIT_RATE_SET_OK = 0,
    TOX_AV_ERR_BIT_RATE_SET_SYNC = 1,
    TOX_AV_ERR_BIT_RATE_SET_INVALID_AUDIO_BIT_RATE = 2,
    TOX_AV_ERR_BIT_RATE_SET_INVALID_VIDEO_BIT_RATE = 3,
    TOX_AV_ERR_BIT_RATE_SET_FRIEND_NOT_FOUND = 4,
    TOX_AV_ERR_BIT_RATE_SET_FRIEND_NOT_IN_CALL = 5,
} TOX_AV_ERR_BIT_RATE_SET;

typedef enum TOX_AV_ERR_SEND_FRAME {
    TOX_AV_ERR_SEND_FRAME_OK = 0,
    TOX_AV_ERR_SEND_FRAME_NULL = 1,
    TOX_AV_ERR_SEND_FRAME_FRIEND_NOT_FOUND = 2,
    TOX_AV_ERR_SEND_FRAME_FRIEND_NOT_IN_CALL = 3,
    TOX_AV_ERR_SEND_FRAME_SYNC = 4,
    TOX_AV_ERR_SEND_FRAME_INVALID = 5,
    TOX_AV_ERR_SEND_FRAME_PAYLOAD_TYPE_DISABLED = 6,
    TOX_AV_ERR_SEND_FRAME_RTP_FAILED = 7,
} TOX_AV_ERR_SEND_FRAME;

// Callback function types matching libtoxcore exactly
typedef void (*toxav_call_cb)(ToxAV *av, uint32_t friend_number, bool audio_enabled, bool video_enabled, void *user_data);
typedef void (*toxav_call_state_cb)(ToxAV *av, uint32_t friend_number, uint32_t state, void *user_data);
typedef void (*toxav_audio_bit_rate_cb)(ToxAV *av, uint32_t friend_number, uint32_t audio_bit_rate, void *user_data);
typedef void (*toxav_video_bit_rate_cb)(ToxAV *av, uint32_t friend_number, uint32_t video_bit_rate, void *user_data);
typedef void (*toxav_audio_receive_frame_cb)(ToxAV *av, uint32_t friend_number, const int16_t *pcm, size_t sample_count, uint8_t channels, uint32_t sampling_rate, void *user_data);
typedef void (*toxav_video_receive_frame_cb)(ToxAV *av, uint32_t friend_number, uint16_t width, uint16_t height, const uint8_t *y, const uint8_t *u, const uint8_t *v, int32_t ystride, int32_t ustride, int32_t vstride, void *user_data);

// Bridge functions to invoke C callbacks from Go
// These are necessary because Go cannot directly call C function pointers

static inline void invoke_call_cb(toxav_call_cb cb, ToxAV *av, uint32_t friend_number, bool audio_enabled, bool video_enabled, void *user_data) {
    if (cb != NULL) {
        cb(av, friend_number, audio_enabled, video_enabled, user_data);
    }
}

static inline void invoke_call_state_cb(toxav_call_state_cb cb, ToxAV *av, uint32_t friend_number, uint32_t state, void *user_data) {
    if (cb != NULL) {
        cb(av, friend_number, state, user_data);
    }
}

static inline void invoke_audio_bit_rate_cb(toxav_audio_bit_rate_cb cb, ToxAV *av, uint32_t friend_number, uint32_t audio_bit_rate, void *user_data) {
    if (cb != NULL) {
        cb(av, friend_number, audio_bit_rate, user_data);
    }
}

static inline void invoke_video_bit_rate_cb(toxav_video_bit_rate_cb cb, ToxAV *av, uint32_t friend_number, uint32_t video_bit_rate, void *user_data) {
    if (cb != NULL) {
        cb(av, friend_number, video_bit_rate, user_data);
    }
}

static inline void invoke_audio_receive_frame_cb(toxav_audio_receive_frame_cb cb, ToxAV *av, uint32_t friend_number, const int16_t *pcm, size_t sample_count, uint8_t channels, uint32_t sampling_rate, void *user_data) {
    if (cb != NULL) {
        cb(av, friend_number, pcm, sample_count, channels, sampling_rate, user_data);
    }
}

static inline void invoke_video_receive_frame_cb(toxav_video_receive_frame_cb cb, ToxAV *av, uint32_t friend_number, uint16_t width, uint16_t height, const uint8_t *y, const uint8_t *u, const uint8_t *v, int32_t ystride, int32_t ustride, int32_t vstride, void *user_data) {
    if (cb != NULL) {
        cb(av, friend_number, width, height, y, u, v, ystride, ustride, vstride, user_data);
    }
}

#line 1 "cgo-generated-wrapper"

#line 3 "toxcore_c.go"

#include <stdint.h>
#include <stdlib.h>

// Callback type for conference messages
typedef void (*group_message_cb)(void *tox, uint32_t conference_number, uint32_t peer_number,
                                 int type, const uint8_t *message, size_t length, void *user_data);

// Callback type for conference invites
typedef void (*group_invite_cb)(void *tox, uint32_t friend_number, int type,
                                const uint8_t *cookie, size_t length, void *user_data);

// Callback type for file receive events
typedef void (*file_recv_cb)(void *tox, uint32_t friend_number, uint32_t file_number,
                             uint32_t kind, uint64_t file_size, const uint8_t *filename,
                             size_t filename_length, void *user_data);

// Callback type for file chunk receive events
typedef void (*file_recv_chunk_cb)(void *tox, uint32_t friend_number, uint32_t file_number,
                                   uint64_t position, const uint8_t *data, size_t length,
                                   void *user_data);

// Callback type for file chunk request events
typedef void (*file_chunk_request_cb)(void *tox, uint32_t friend_number, uint32_t file_number,
                                      uint64_t position, size_t length, void *user_data);

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// toxav_new creates a new ToxAV instance from a Tox instance.
//
// This function matches the libtoxcore toxav_new API exactly.
//
extern void* toxav_new(void* tox, TOX_AV_ERR_NEW* error_ptr);

// toxav_kill gracefully shuts down a ToxAV instance.
//
// This function matches the libtoxcore toxav_kill API exactly.
//
extern void toxav_kill(void* av);

// toxav_get_tox_from_av returns the Tox instance associated with ToxAV.
//
// This function matches the libtoxcore toxav_get_tox_from_av API exactly.
//
extern void* toxav_get_tox_from_av(void* av);

// toxav_iteration_interval returns the iteration interval for ToxAV.
//
// This function matches the libtoxcore toxav_iteration_interval API exactly.
//
extern uint32_t toxav_iteration_interval(void* av);

// toxav_iterate performs one iteration of the ToxAV event loop.
//
// This function matches the libtoxcore toxav_iterate API exactly.
//
extern void toxav_iterate(void* av);

// toxav_call initiates an audio/video call.
//
// This function matches the libtoxcore toxav_call API exactly.
//
extern _Bool toxav_call(void* av, uint32_t friend_number, uint32_t audio_bit_rate, uint32_t video_bit_rate, TOX_AV_ERR_CALL* error_ptr);

// toxav_answer accepts an incoming audio/video call.
//
// This function matches the libtoxcore toxav_answer API exactly.
//
extern _Bool toxav_answer(void* av, uint32_t friend_number, uint32_t audio_bit_rate, uint32_t video_bit_rate, TOX_AV_ERR_ANSWER* error_ptr);

// toxav_call_control sends a call control command.
//
// This function matches the libtoxcore toxav_call_control API exactly.
//
extern _Bool toxav_call_control(void* av, uint32_t friend_number, TOX_AV_CALL_CONTROL control, TOX_AV_ERR_CALL_CONTROL* error_ptr);

// toxav_audio_set_bit_rate sets the audio bit rate for a call.
//
// This function matches the libtoxcore toxav_audio_set_bit_rate API exactly.
//
extern _Bool toxav_audio_set_bit_rate(void* av, uint32_t friend_number, uint32_t bit_rate, TOX_AV_ERR_BIT_RATE_SET* error_ptr);

// toxav_video_set_bit_rate sets the video bit rate for a call.
//
// This function matches the libtoxcore toxav_video_set_bit_rate API exactly.
//
extern _Bool toxav_video_set_bit_rate(void* av, uint32_t friend_number, uint32_t bit_rate, TOX_AV_ERR_BIT_RATE_SET* error_ptr);

// toxav_audio_send_frame sends an audio frame.
//
// This function matches the libtoxcore toxav_audio_send_frame API exactly.
//
extern _Bool toxav_audio_send_frame(void* av, uint32_t friend_number, int16_t* pcm, size_t sample_count, uint8_t channels, uint32_t sampling_rate, TOX_AV_ERR_SEND_FRAME* error_ptr);

// toxav_video_send_frame sends a video frame.
//
// This function matches the libtoxcore toxav_video_send_frame API exactly.
//
extern _Bool toxav_video_send_frame(void* av, uint32_t friend_number, uint16_t width, uint16_t height, uint8_t* y, uint8_t* u, uint8_t* v, TOX_AV_ERR_SEND_FRAME* error_ptr);
extern void toxav_callback_call(void* av, toxav_call_cb callback, void* user_data);
extern void toxav_callback_call_state(void* av, toxav_call_state_cb callback, void* user_data);
extern void toxav_callback_audio_bit_rate(void* av, toxav_audio_bit_rate_cb callback, void* user_data);
extern void toxav_callback_video_bit_rate(void* av, toxav_video_bit_rate_cb callback, void* user_data);
extern void toxav_callback_audio_receive_frame(void* av, toxav_audio_receive_frame_cb callback, void* user_data);
extern void toxav_callback_video_receive_frame(void* av, toxav_video_receive_frame_cb callback, void* user_data);
extern void* tox_new();
extern void tox_kill(void* tox);
extern GoInt tox_bootstrap_simple(void* tox);
extern void tox_iterate(void* tox);
extern GoInt tox_iteration_interval(void* tox);
extern GoInt tox_self_get_address_size(void* tox);
extern GoInt hex_string_to_bin(GoUint8* hexStr, GoInt hexLen, GoUint8* output, GoInt outputLen);

// tox_self_get_address copies the Tox address to the provided buffer.
// The buffer must be at least TOX_ADDRESS_SIZE (38) bytes.
// Returns 0 on success, -1 on error.
//
extern GoInt tox_self_get_address(void* tox, GoUint8* address);

// tox_self_get_public_key copies the public key to the provided buffer.
// The buffer must be at least TOX_PUBLIC_KEY_SIZE (32) bytes.
// Returns 0 on success, -1 on error.
//
extern GoInt tox_self_get_public_key(void* tox, GoUint8* publicKey);

// tox_friend_add adds a friend by Tox address and sends a friend request message.
// Returns the friend number on success, or UINT32_MAX on failure.
//
extern GoUint32 tox_friend_add(void* tox, GoUint8* address, GoUint8* message, GoInt messageLen);

// tox_friend_add_norequest adds a friend by public key without sending a request.
// Use this to accept incoming friend requests.
// Returns the friend number on success, or UINT32_MAX on failure.
//
extern GoUint32 tox_friend_add_norequest(void* tox, GoUint8* publicKey);

// tox_friend_delete removes a friend from the friends list.
// Returns 0 on success, -1 on failure.
//
extern GoInt tox_friend_delete(void* tox, GoUint32 friendNumber);

// tox_friend_send_message sends a message to a friend.
// messageType: 0 = normal message, 1 = action message.
// Returns the message ID on success (always 1 for now), or 0 on failure.
//
extern GoUint32 tox_friend_send_message(void* tox, GoUint32 friendNumber, GoInt messageType, GoUint8* message, GoInt messageLen);

// tox_callback_friend_request registers a callback for friend requests.
// The callback receives: tox pointer, public key (32 bytes), message, message length, user data.
//
extern void tox_callback_friend_request(void* tox, void* callback, void* userData);

// tox_callback_friend_message registers a callback for friend messages.
// The callback receives: tox pointer, friend number, message type, message, message length, user data.
//
extern void tox_callback_friend_message(void* tox, void* callback, void* userData);

// tox_callback_friend_connection_status registers a callback for friend connection status changes.
// The callback receives: tox pointer, friend number, connection status, user data.
//
extern void tox_callback_friend_connection_status(void* tox, void* callback, void* userData);

// tox_self_set_name sets the name of this Tox instance.
// Returns 0 on success, -1 on error.
//
extern GoInt tox_self_set_name(void* tox, GoUint8* name, GoInt nameLen);

// tox_self_get_name_size returns the length of the name.
//
extern GoInt tox_self_get_name_size(void* tox);

// tox_self_get_name copies the name to the provided buffer.
// Returns 0 on success, -1 on error.
//
extern GoInt tox_self_get_name(void* tox, GoUint8* name);

// tox_self_set_status_message sets the status message of this Tox instance.
// Returns 0 on success, -1 on error.
//
extern GoInt tox_self_set_status_message(void* tox, GoUint8* message, GoInt messageLen);

// tox_self_get_status_message_size returns the length of the status message.
//
extern GoInt tox_self_get_status_message_size(void* tox);

// tox_self_get_status_message copies the status message to the provided buffer.
// Returns 0 on success, -1 on error.
//
extern GoInt tox_self_get_status_message(void* tox, GoUint8* message);

// tox_conference_new creates a new conference (group chat).
// Returns the conference ID on success, or UINT32_MAX on failure.
//
extern GoUint32 tox_conference_new(void* tox, GoUint32* err);

// tox_conference_invite invites a friend to a conference.
// Returns 0 on success, non-zero on error.
//
extern GoInt tox_conference_invite(void* tox, GoUint32 friendID, GoUint32 conferenceID, GoUint32* err);

// tox_conference_send_message sends a message to a conference.
// Returns 0 on success, non-zero on error.
//
extern GoInt tox_conference_send_message(void* tox, GoUint32 conferenceID, GoInt msgType, GoUint8* message, GoUint32 length, GoUint32* err);

// tox_conference_delete leaves and deletes a conference.
// Returns 0 on success, non-zero on error.
//
extern GoInt tox_conference_delete(void* tox, GoUint32 conferenceID, GoUint32* err);

// tox_conference_get_title gets the title of a conference.
// Returns the length of the title on success, or -1 on error.
//
extern GoInt tox_conference_get_title_size(void* tox, GoUint32 conferenceID, GoUint32* err);

// tox_callback_conference_message sets the callback for conference message events.
//
extern void tox_callback_conference_message(void* tox, group_message_cb callback);

// tox_callback_conference_invite sets the callback for conference invite events.
//
extern void tox_callback_conference_invite(void* tox, group_invite_cb callback);

// tox_file_send sends a file send request.
// Returns the file number on success, or UINT32_MAX on failure.
//
extern GoUint32 tox_file_send(void* tox, GoUint32 friendID, GoUint32 kind, GoUint64 fileSize, GoUint8* fileID, GoUint8* filename, GoUint32 filenameLen, GoUint32* err);

// tox_file_control controls an ongoing file transfer.
// Returns 0 on success, non-zero on error.
//
extern GoInt tox_file_control(void* tox, GoUint32 friendID, GoUint32 fileID, GoInt control, GoUint32* err);

// tox_file_send_chunk sends a chunk of a file being transferred.
// Returns 0 on success, non-zero on error.
//
extern GoInt tox_file_send_chunk(void* tox, GoUint32 friendID, GoUint32 fileID, GoUint64 position, GoUint8* data, GoUint32 length, GoUint32* err);

// tox_callback_file_recv sets the callback for file receive events.
//
extern void tox_callback_file_recv(void* tox, file_recv_cb callback);

// tox_callback_file_recv_chunk sets the callback for file chunk receive events.
//
extern void tox_callback_file_recv_chunk(void* tox, file_recv_chunk_cb callback);

// tox_callback_file_chunk_request sets the callback for file chunk request events.
//
extern void tox_callback_file_chunk_request(void* tox, file_chunk_request_cb callback);

#ifdef __cplusplus
}
#endif
