// Code generated by gen-bootstrap-nodes; DO NOT EDIT.
// Source: https://nodes.tox.chat/json
// Generated: 2026-04-12T00:00:00Z

package nodes

// DefaultNodes is the list of default Tox DHT bootstrap nodes.
// This list is automatically generated from the canonical node list.
var DefaultNodes = []NodeInfo{
	{Address: "144.217.167.73", Port: 33445, PublicKey: "7E5668E0EE09E19F320AD47902419331FFEE147BB3606769CFBE921A2A2FD34C", Maintainer: "velusip"},
	{Address: "tox.abilinski.com", Port: 33445, PublicKey: "10C00EB250C3233E343E2AEBA07115A5C28920E9C8D29492F6D00B29049EDC7E", Maintainer: "AnthonyBilinski"},
	{Address: "node.tox.biribiri.org", Port: 33445, PublicKey: "F404ABAA1C99A9D37D61AB54898F56793E1DEF8BD46B1038B9D822E8460FAB67", Maintainer: "nurupo"},
	{Address: "tox.verdict.gg", Port: 33445, PublicKey: "1C5293AEF2114717547B39DA8EA6F1E331E5E358B35F9B6B5F19317911C5F976", Maintainer: "Deliran"},
	{Address: "tox.initramfs.io", Port: 33445, PublicKey: "3F0A45A268367C1BEA652F258C85F4A66DA76BCAA667A49E770BCC4917AB6A25", Maintainer: "initramfs"},
	{Address: "tox.kurnevsky.net", Port: 33445, PublicKey: "82EF82BA33445A1F91A7DB27189ECFC0C013E06E3DA71F588ED692BED625EC23", Maintainer: "kurnevsky"},
	{Address: "205.185.115.131", Port: 53, PublicKey: "3091C6BEB2A993F1C6300C16549FABA67098FF3D62C6D253828B531470B53D68", Maintainer: "ray65536"},
	{Address: "46.101.197.175", Port: 33445, PublicKey: "CD133B521159541FB1D326DE9850F5E56A6C724B5B8E5EB5CD8D950408E95707", Maintainer: "clearmartin"},
}
