// Command gen-bootstrap-nodes fetches the canonical Tox bootstrap node list
// from https://nodes.tox.chat/json, filters for online UDP nodes, and generates
// a Go source file at bootstrap/nodes/default_nodes.go.
package main

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"time"
)

const (
	sourceURL     = "https://nodes.tox.chat/json"
	outputFile    = "bootstrap/nodes/default_nodes.go"
	minValidNodes = 4
)

// toxNode represents a single entry from the upstream JSON node list.
type toxNode struct {
	IPV4       string `json:"ipv4"`
	IPV6       string `json:"ipv6"`
	Port       uint16 `json:"port"`
	PublicKey  string `json:"public_key"`
	Maintainer string `json:"maintainer"`
	StatusUDP  bool   `json:"status_udp"`
	LastPing   int64  `json:"last_ping"`
}

// nodeList represents the top-level JSON structure from nodes.tox.chat.
type nodeList struct {
	Nodes []toxNode `json:"nodes"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-bootstrap-nodes: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	data, err := fetchNodeList(sourceURL)
	if err != nil {
		return fmt.Errorf("fetching node list: %w", err)
	}

	nodes, err := parseAndFilter(data)
	if err != nil {
		return fmt.Errorf("parsing node list: %w", err)
	}

	if len(nodes) < minValidNodes {
		return fmt.Errorf("only %d valid nodes found, need at least %d", len(nodes), minValidNodes)
	}

	outPath := resolveOutputPath()
	if err := writeGeneratedFile(outPath, generateSource(nodes)); err != nil {
		return err
	}

	fmt.Printf("Generated %s with %d bootstrap nodes\n", outPath, len(nodes))
	return nil
}

// resolveOutputPath determines the correct output file path based on the
// execution context (go:generate, repo root, or runtime-derived fallback).
func resolveOutputPath() string {
	if goPkg := os.Getenv("GOPACKAGE"); goPkg == "nodes" {
		return "default_nodes.go"
	}
	if _, err := os.Stat("bootstrap"); os.IsNotExist(err) {
		_, sourceFile, _, ok := runtime.Caller(0)
		if ok {
			repoRoot := filepath.Dir(filepath.Dir(filepath.Dir(sourceFile)))
			candidate := filepath.Join(repoRoot, outputFile)
			if _, err := os.Stat(filepath.Dir(candidate)); err == nil {
				return candidate
			}
		}
	}
	return outputFile
}

// writeGeneratedFile writes src to outPath (creating the directory if needed)
// and runs gofmt on the result.
func writeGeneratedFile(outPath, src string) error {
	if dir := filepath.Dir(outPath); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("creating output directory: %w", err)
		}
	}
	if err := os.WriteFile(outPath, []byte(src), 0o644); err != nil {
		return fmt.Errorf("writing output file: %w", err)
	}
	gofmtBin := "gofmt"
	if runtime.GOOS == "windows" {
		gofmtBin = "gofmt.exe"
	}
	if out, err := exec.Command(gofmtBin, "-w", outPath).CombinedOutput(); err != nil {
		return fmt.Errorf("running gofmt: %w\n%s", err, out)
	}
	return nil
}

func fetchNodeList(url string) ([]byte, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("HTTP request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("HTTP %d from %s", resp.StatusCode, url)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("reading response body: %w", err)
	}

	return data, nil
}

// parseAndFilter parses the JSON data and returns UDP-online nodes with
// required fields, normalized public keys, and a descending LastPing sort.
func parseAndFilter(data []byte) ([]toxNode, error) {
	var list nodeList
	if err := json.Unmarshal(data, &list); err != nil {
		return nil, fmt.Errorf("JSON parse error: %w", err)
	}

	var valid []toxNode
	for _, n := range list.Nodes {
		if normalized, ok := normalizeNode(n); ok {
			valid = append(valid, normalized)
		}
	}

	sort.Slice(valid, func(i, j int) bool {
		return valid[i].LastPing > valid[j].LastPing
	})

	return valid, nil
}

// normalizeNode validates a node entry and returns a normalized copy.
// Returns (normalized, true) if the node is a valid, online UDP node; otherwise (zero, false).
func normalizeNode(n toxNode) (toxNode, bool) {
	if !n.StatusUDP {
		return toxNode{}, false
	}
	if n.IPV4 == "" || n.PublicKey == "" || n.Port == 0 {
		return toxNode{}, false
	}
	n.PublicKey = strings.ToUpper(n.PublicKey)
	if len(n.PublicKey) != 64 {
		return toxNode{}, false
	}
	if _, err := hex.DecodeString(n.PublicKey); err != nil {
		return toxNode{}, false
	}
	return n, true
}

func generateSource(nodes []toxNode) string {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by gen-bootstrap-nodes; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Source: %s\n", sourceURL)
	fmt.Fprintf(&buf, "\n")
	fmt.Fprintf(&buf, "package nodes\n\n")
	fmt.Fprintf(&buf, "// DefaultNodes is the list of default Tox DHT bootstrap nodes.\n")
	fmt.Fprintf(&buf, "// This list is automatically generated from the canonical node list.\n")
	fmt.Fprintf(&buf, "var DefaultNodes = []NodeInfo{\n")

	for _, n := range nodes {
		fmt.Fprintf(&buf, "\t{Address: %q, Port: %d, PublicKey: %q, Maintainer: %q},\n",
			n.IPV4, n.Port, n.PublicKey, n.Maintainer)
	}

	fmt.Fprintf(&buf, "}\n")

	return buf.String()
}
